global using Microsoft.EntityFrameworkCore;
global using Domain.Users;
global using Infrastructure.Contexts;
global using Microsoft.Extensions.DependencyInjection;
global using Infrastructure.Repositories;
global using Domain.Commons;
global using Domain.Posts;
global using Domain.Stories;
global using Domain.Messages;